# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: yawaflua
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_timezone: Asia/Jerusalem
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: yawaflua/HallOfDoors, yawaflua/ShardLight, yawaflua/sigma_market, yawaflua/hall_of_doors, yawaflua/shardlight-web-panel, yawaflua/AskMeAboutBot, yawaflua/binarshina, yawaflua/SpectrBot, yawaflua/shardlight-harmony, yawaflua/Plinko.Games.Elysium, yawaflua/Dice.Elysium, yawaflua/ElysiumChat, yawaflua/FireWatch, yawaflua/S3-Container, yawaflua/SkinsApi, yawaflua/FileSender, yawaflua/PSQL_backupper, yawaflua/TGShock, yawaflua/BiahadHakatonProject, yawaflua/WebSockets, yawaflua/Telegram.Net, yawaflua/PixelTalk, yawaflua/SPMega, yawaflua/vue.yawaflua.ru, yawaflua/react-frontend.yawaflua.ru, yawaflua/api.yawaflua.ru, yawaflua/Aoyo, yawaflua/TheatreCube, yawaflua/tzeva-adom, yawaflua/SpCloudCore, yawaflua/Discord.Net, yawaflua/Aoyo.Taiga, yawaflua/OrderHabrFreelance, yawaflua/PL_JusticeBot, yawaflua/Q-FordBot, yawaflua/oembed-tests.yawaflua.ru, yawaflua/SPWorlds, yawaflua/Telegram-Bot-Template, yawaflua/SeaBattle, yawaflua/SpCloudAdmin, yawaflua/Go.Template.Elysium, yawaflua/TestAnswer, yawaflua/SexPlugin, yawaflua/frontend.yawaflua.ru
          plugin_languages_recent_load: 9999
          plugin_languages_recent_days: 9999
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
